// src/presentation/components/sections/MotivationSection.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<template>
  <section id="motivation" class="section bg-transparent section-padding" data-section="motivation">
    <!-- Content -->
    <div class="section-content flex flex-col justify-center items-center h-full">
      <div class="section-header w-full reveal">
        <h2 class="text-[var(--color-terminal-green)] mb-2">{{ t('motivation.title') }}</h2>
        <p class="section-subtitle">{{ t('motivation.subtitle') }}</p>
      </div>

      <div class="flex flex-col gap-4 w-full max-w-[800px] xl:max-w-[1000px] 2xl:max-w-[1200px]">
        <!-- Ideal Environment -->
        <div class="space-y-3 reveal">
          <div class="bg-[#0A0A0A]/60 backdrop-blur-md border border-purple-500/15 rounded-lg flex items-start gap-3 py-4 px-5 transition-[background-color,border-color,box-shadow] duration-150 hover:bg-[#0A0A0A]/80 hover:border-purple-500/30 hover:shadow-lg hover:shadow-purple-500/10">
            <span class="text-2xl shrink-0 mt-0.5">🌱</span>
            <p class="text-sm leading-relaxed text-white/70 m-0 flex-1">{{ t('motivation.culture.idealEnvironment.description') }}</p>
          </div>
        </div>

        <!-- Management Styles -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <!-- My Management Style -->
          <div class="space-y-3 reveal" :style="{ '--reveal-i': 1 }">
            <h3 class="text-lg font-semibold text-white/90 text-center mb-1">{{ t('motivation.managementStyle.adopts.title') }}</h3>
            <div class="bg-[#0A0A0A]/60 backdrop-blur-md border border-purple-500/15 rounded-lg flex items-start gap-3 py-4 px-5 transition-all duration-150 hover:bg-[#0A0A0A]/80 hover:border-purple-500/30 hover:shadow-lg hover:shadow-purple-500/10">
              <span class="text-2xl shrink-0 mt-0.5">👁️</span>
              <div class="flex-1">
                <div class="text-sm font-medium text-white/90 mb-2">{{ t('motivation.managementStyle.adopts.implication.title') }}</div>
                <p class="text-sm leading-relaxed text-white/70 m-0">{{ t('motivation.managementStyle.adopts.implication.description') }}</p>
              </div>
            </div>
          </div>

          <!-- Management Style I Seek -->
          <div class="space-y-3 reveal" :style="{ '--reveal-i': 2 }">
            <h3 class="text-lg font-semibold text-white/90 text-center mb-1">{{ t('motivation.managementStyle.seeks.title') }}</h3>
            <div class="bg-[#0A0A0A]/60 backdrop-blur-md border border-[color-mix(in_srgb,var(--color-accent-cool)_18%,transparent)] rounded-lg flex items-start gap-3 py-4 px-5 transition-[background-color,border-color,box-shadow] duration-150 hover:bg-[#0A0A0A]/80 hover:border-[color-mix(in_srgb,var(--color-accent-cool)_35%,transparent)] hover:shadow-lg hover:shadow-cyan-500/10">
              <span class="text-2xl shrink-0 mt-0.5">🎯</span>
              <p class="text-sm leading-relaxed text-white/70 m-0 flex-1">{{ t('motivation.managementStyle.seeks.description') }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// src/presentation/components/sections/MotivationSection.tsx
import type { CSSProperties } from 'react'
import { useTranslation } from 'react-i18next'

export default function MotivationSection() {
  const { t } = useTranslation()

  return (
    <section id="motivation" className="section bg-transparent section-padding" data-section="motivation">
      {/* Content */}
      <div className="section-content flex flex-col justify-center items-center h-full">
        <div className="section-header w-full reveal">
          <h2 className="text-[var(--color-terminal-green)] mb-2">{t('motivation.title')}</h2>
          <p className="section-subtitle">{t('motivation.subtitle')}</p>
        </div>

        <div className="flex flex-col gap-4 w-full max-w-[800px] xl:max-w-[1000px] 2xl:max-w-[1200px]">
          {/* Ideal Environment */}
          <div className="space-y-3 reveal">
            <div className="bg-[#0A0A0A]/60 backdrop-blur-md border border-purple-500/15 rounded-lg flex items-start gap-3 py-4 px-5 transition-[background-color,border-color,box-shadow] duration-150 hover:bg-[#0A0A0A]/80 hover:border-purple-500/30 hover:shadow-lg hover:shadow-purple-500/10">
              <span className="text-2xl shrink-0 mt-0.5">🌱</span>
              <p className="text-sm leading-relaxed text-white/70 m-0 flex-1">{t('motivation.culture.idealEnvironment.description')}</p>
            </div>
          </div>

          {/* Management Styles */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* My Management Style */}
            <div className="space-y-3 reveal" style={{ '--reveal-i': 1 } as CSSProperties}>
              <h3 className="text-lg font-semibold text-white/90 text-center mb-1">{t('motivation.managementStyle.adopts.title')}</h3>
              <div className="bg-[#0A0A0A]/60 backdrop-blur-md border border-purple-500/15 rounded-lg flex items-start gap-3 py-4 px-5 transition-all duration-150 hover:bg-[#0A0A0A]/80 hover:border-purple-500/30 hover:shadow-lg hover:shadow-purple-500/10">
                <span className="text-2xl shrink-0 mt-0.5">👁️</span>
                <div className="flex-1">
                  <div className="text-sm font-medium text-white/90 mb-2">{t('motivation.managementStyle.adopts.implication.title')}</div>
                  <p className="text-sm leading-relaxed text-white/70 m-0">{t('motivation.managementStyle.adopts.implication.description')}</p>
                </div>
              </div>
            </div>

            {/* Management Style I Seek */}
            <div className="space-y-3 reveal" style={{ '--reveal-i': 2 } as CSSProperties}>
              <h3 className="text-lg font-semibold text-white/90 text-center mb-1">{t('motivation.managementStyle.seeks.title')}</h3>
              <div className="bg-[#0A0A0A]/60 backdrop-blur-md border border-[color-mix(in_srgb,var(--color-accent-cool)_18%,transparent)] rounded-lg flex items-start gap-3 py-4 px-5 transition-[background-color,border-color,box-shadow] duration-150 hover:bg-[#0A0A0A]/80 hover:border-[color-mix(in_srgb,var(--color-accent-cool)_35%,transparent)] hover:shadow-lg hover:shadow-cyan-500/10">
                <span className="text-2xl shrink-0 mt-0.5">🎯</span>
                <p className="text-sm leading-relaxed text-white/70 m-0 flex-1">{t('motivation.managementStyle.seeks.description')}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
