// src/presentation/components/three/scenes/maker/units/UdmProUnit.vue
<script setup lang="ts">
import type { ServerUnit } from '@domain/types/makerRack'
import type { makerColors } from '@domain/data/makerRack'
import { sharedMaterials } from '@application/composables/useSharedGeometries'
import BaseServerUnit from '../BaseServerUnit.vue'

interface AnimationState {
    time: number
    fanRotation: number
}

interface Props {
    unit: ServerUnit
    isHovered: boolean
    anim: AnimationState
    colors: typeof makerColors
}

defineProps<Props>()
</script>

<template>
    <BaseServerUnit :unit="unit" :is-hovered="isHovered" :colors="colors">
        <!-- Small display area -->
        <TresMesh :position="[-0.181, 0, 0.37]" :material="sharedMaterials.darkMetal">
            <TresPlaneGeometry :args="[0.4, 0.15]" />
        </TresMesh>
    </BaseServerUnit>
</template>

// src/presentation/components/three/scenes/maker/units/UdmProUnit.tsx
import type { ServerUnit } from '@domain/types/makerRack'
import type { makerColors } from '@domain/data/makerRack'
import { sharedMaterials } from '@application/hooks/useSharedGeometries'
import BaseServerUnit from '../BaseServerUnit'

interface AnimationState {
    time: number
    fanRotation: number
}

interface Props {
    unit: ServerUnit
    isHovered: boolean
    anim: AnimationState
    colors: typeof makerColors
}

export default function UdmProUnit({ unit, isHovered, colors }: Props) {
    return (
        <BaseServerUnit unit={unit} isHovered={isHovered} colors={colors}>
            {/* Small display area */}
            <mesh position={[-0.181, 0, 0.37]} material={sharedMaterials.darkMetal}>
                <planeGeometry args={[0.4, 0.15]} />
            </mesh>
        </BaseServerUnit>
    )
}
