// src/App.tsx
import { useEffect, useRef } from 'react'
import { Outlet, useLocation } from 'react-router'
import LanguageSwitcher from '@presentation/components/ui/LanguageSwitcher'
import AchievementToast from '@presentation/components/ui/AchievementToast'
import AchievementsIndicator from '@presentation/components/ui/AchievementsIndicator'
import FPSDisplay from '@presentation/components/ui/FPSDisplay'
import type { FPSDisplayHandle } from '@presentation/components/ui/FPSDisplay'
import TableOfContents from '@presentation/components/ui/TableOfContents'
import CompanionOverlay from '@presentation/components/ui/CompanionOverlay'
import AppBackground from '@presentation/components/ui/AppBackground'
import { useAchievements } from '@application/hooks/useAchievements'
import { useEasterEggs } from '@application/hooks/useEasterEggs'
import { startFPSMonitoring } from '@application/hooks/useQuality'
import { useAchievementsStore } from '@application/stores/achievements'

const VISIT_STORAGE_KEY = 'wifsimster_visit_count'
const VISIT_DAYS_STORAGE_KEY = 'wifsimster_visit_days'

export default function App() {
  const { currentAchievement, showAchievement, dismissAchievement } = useAchievements()

  // Initialize easter eggs listener
  const { fpsEnabled } = useEasterEggs()

  // FPS display ref
  const fpsDisplayRef = useRef<FPSDisplayHandle>(null)

  const location = useLocation()

  // Watch for FPS enable/disable
  useEffect(() => {
    if (!fpsDisplayRef.current) return
    if (fpsEnabled) {
      fpsDisplayRef.current.start()
    } else {
      fpsDisplayRef.current.stop()
    }
  }, [fpsEnabled])

  // Hash navigation: scroll to the section targeted by #hash (vue-router
  // scrollBehavior equivalent)
  useEffect(() => {
    if (!location.hash) return
    const hash = location.hash
    const element = document.querySelector(hash)
      ?? document.querySelector(`[data-section="${hash.slice(1)}"]`)
    element?.scrollIntoView({ behavior: 'smooth' })
  }, [location.hash])

  useEffect(() => {
    const { unlock, isUnlocked } = useAchievementsStore.getState()

    // Guard the FPS target: the monitor auto-degrades quality (high → low →
    // minimal) whenever sustained FPS falls below 70% of the target, so the
    // higher desktop DPR/texture budget can never lock the page under 60fps.
    startFPSMonitoring()

    // Auto-enable FPS display in development
    if (import.meta.env.DEV && fpsDisplayRef.current) {
      fpsDisplayRef.current.start()
    }

    // Check visit-related achievements
    const visitCount = parseInt(localStorage.getItem(VISIT_STORAGE_KEY) || '0', 10)
    if (visitCount === 0) {
      unlock('firstVisit')
    } else {
      unlock('returnVisitor')
    }
    localStorage.setItem(VISIT_STORAGE_KEY, String(visitCount + 1))

    // Check time-based achievements
    const hour = new Date().getHours()
    const day = new Date().getDay()

    // Early bird: 5AM - 8AM
    if (hour >= 5 && hour < 8) {
      unlock('earlyBird')
    }

    // Night owl: 10PM - 5AM
    if (hour >= 22 || hour < 5) {
      unlock('nightOwl')
    }

    // Night explorer: midnight - 3AM
    if (hour >= 0 && hour < 4) {
      unlock('nightExplorer')
    }

    // Weekend warrior: Saturday (6) or Sunday (0)
    if (day === 0 || day === 6) {
      unlock('weekendWarrior')
    }

    // Check 3D load completion for patience achievement: unlock after page
    // fully loads (including 3D)
    const handleLoad = () => {
      setTimeout(() => {
        unlock('patience')
      }, 3000) // Wait 3 seconds after full load
    }
    window.addEventListener('load', handleLoad, { once: true })

    // Check device type
    if (navigator.maxTouchPoints > 0 && window.innerWidth < 768) {
      unlock('mobileScout')
    }

    // Track unique visit days for frequent flyer
    const today = new Date().toISOString().split('T')[0]
    const savedDays = JSON.parse(localStorage.getItem(VISIT_DAYS_STORAGE_KEY) || '[]') as string[]
    if (!savedDays.includes(today)) {
      savedDays.push(today)
      localStorage.setItem(VISIT_DAYS_STORAGE_KEY, JSON.stringify(savedDays))
    }
    if (savedDays.length >= 3) {
      unlock('frequentFlyer')
    }

    // Listen for print attempts
    const handleBeforePrint = () => {
      unlock('printReady')
    }
    window.addEventListener('beforeprint', handleBeforePrint)

    // Track time spent
    const startTime = Date.now()
    const timeSpentInterval = setInterval(() => {
      const elapsed = (Date.now() - startTime) / 1000 / 60 // minutes
      if (elapsed >= 5 && !isUnlocked('timeSpent')) {
        unlock('timeSpent')
      }
      if (elapsed >= 10 && !isUnlocked('devotedReader')) {
        unlock('devotedReader')
      }
      if (isUnlocked('timeSpent') && isUnlocked('devotedReader')) {
        clearInterval(timeSpentInterval)
      }
    }, 10000) // Check every 10 seconds

    // Track clicks
    let clickCount = 0
    const handleClick = () => {
      clickCount++
      if (clickCount >= 50 && !isUnlocked('clickHappy')) {
        unlock('clickHappy')
      }
    }

    // Track scroll distance
    let totalScrolled = 0
    let lastScrollY = window.scrollY
    let reachedBottom = false
    const handleScroll = () => {
      const currentScrollY = window.scrollY
      const scrollDiff = Math.abs(currentScrollY - lastScrollY)
      totalScrolled += scrollDiff
      lastScrollY = currentScrollY

      if (totalScrolled >= 10000 && !isUnlocked('scrollMaster')) {
        unlock('scrollMaster')
      }

      // Boomerang: scrolled to bottom then back to top
      const scrollHeight = document.documentElement.scrollHeight
      const clientHeight = document.documentElement.clientHeight
      const scrollPercent = currentScrollY / (scrollHeight - clientHeight)

      if (scrollPercent >= 0.99) {
        reachedBottom = true
      }
      if (reachedBottom && scrollPercent < 0.01 && !isUnlocked('boomerang')) {
        unlock('boomerang')
      }
    }

    // Track Tab key presses
    let tabKeyCount = 0
    const handleKeyboardTracking = (e: KeyboardEvent) => {
      if (e.key === 'Tab') {
        tabKeyCount++
        if (tabKeyCount >= 10 && !isUnlocked('keyboardNinja')) {
          unlock('keyboardNinja')
        }
      }
    }

    // Buffer keystrokes and detect secret words
    let secretBuffer = ''
    const handleSecretWord = (e: KeyboardEvent) => {
      if (e.key.length === 1) {
        secretBuffer += e.key.toLowerCase()
        // Keep buffer manageable
        if (secretBuffer.length > 20) {
          secretBuffer = secretBuffer.slice(-20)
        }
        if (secretBuffer.includes('hello') || secretBuffer.includes('bonjour')) {
          unlock('secretWhisper')
          secretBuffer = ''
        }
      }
    }

    window.addEventListener('click', handleClick)
    window.addEventListener('scroll', handleScroll, { passive: true })
    window.addEventListener('keydown', handleKeyboardTracking)
    window.addEventListener('keydown', handleSecretWord)

    return () => {
      window.removeEventListener('load', handleLoad)
      window.removeEventListener('click', handleClick)
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('keydown', handleKeyboardTracking)
      window.removeEventListener('keydown', handleSecretWord)
      window.removeEventListener('beforeprint', handleBeforePrint)
      clearInterval(timeSpentInterval)
    }
  }, [])

  return (
    <div className="min-h-screen bg-(--color-bg-primary)">
      {/* Modern aurora-mesh backdrop behind everything */}
      <AppBackground />

      {/* Fixed UI Elements */}
      <header className="fixed top-4 right-4 z-100 flex gap-3 items-center sm:top-2 sm:right-2 sm:gap-2">
        <AchievementsIndicator />
        <LanguageSwitcher />
      </header>

      {/* Table of Contents (Desktop only) */}
      <TableOfContents />

      {/* Main Content */}
      <Outlet />

      {/* Three.js space companion cruising across every section */}
      <CompanionOverlay />

      {/* Achievement Toast */}
      {showAchievement && currentAchievement && (
        <AchievementToast
          achievement={currentAchievement}
          onClose={dismissAchievement}
        />
      )}

      {/* FPS Display */}
      <FPSDisplay ref={fpsDisplayRef} />
    </div>
  )
}

// src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, nextTick } from 'vue'
import { RouterView } from 'vue-router'
import LanguageSwitcher from '@presentation/components/ui/LanguageSwitcher.vue'
import AchievementToast from '@presentation/components/ui/AchievementToast.vue'
import AchievementsIndicator from '@presentation/components/ui/AchievementsIndicator.vue'
import FPSDisplay from '@presentation/components/ui/FPSDisplay.vue'
import TableOfContents from '@presentation/components/ui/TableOfContents.vue'
import CompanionOverlay from '@presentation/components/ui/CompanionOverlay.vue'
import AppBackground from '@presentation/components/ui/AppBackground.vue'
import { useAchievements } from '@application/composables/useAchievements'
import { useEasterEggs } from '@application/composables/useEasterEggs'
import { useQuality } from '@application/composables/useQuality'

const { currentAchievement, showAchievement, dismissAchievement, unlock, isUnlocked } = useAchievements()

// Initialize easter eggs listener
const { fpsEnabled } = useEasterEggs()

// Quality auto-degradation (guards the 60fps target on every tier)
const { startFPSMonitoring } = useQuality()

// FPS display ref
const fpsDisplayRef = ref<InstanceType<typeof FPSDisplay> | null>(null)

// Watch for FPS enable/disable
watch(fpsEnabled, async (enabled) => {
  await nextTick()
  if (fpsDisplayRef.value) {
    if (enabled) {
      fpsDisplayRef.value.start()
    } else {
      fpsDisplayRef.value.stop()
    }
  }
})

// Tracking state
const clickCount = ref(0)
const totalScrolled = ref(0)
const lastScrollY = ref(0)
const reachedBottom = ref(false)
const tabKeyCount = ref(0)
const secretBuffer = ref('')
const timeSpentInterval = ref<ReturnType<typeof setInterval> | null>(null)

const VISIT_STORAGE_KEY = 'wifsimster_visit_count'

// Check visit-related achievements
const checkVisitAchievements = () => {
  const visitCount = parseInt(localStorage.getItem(VISIT_STORAGE_KEY) || '0', 10)
  
  if (visitCount === 0) {
    unlock('firstVisit')
  } else {
    unlock('returnVisitor')
  }
  
  localStorage.setItem(VISIT_STORAGE_KEY, String(visitCount + 1))
}

// Check time-based achievements
const checkTimeAchievements = () => {
  const hour = new Date().getHours()
  const day = new Date().getDay()

  // Early bird: 5AM - 8AM
  if (hour >= 5 && hour < 8) {
    unlock('earlyBird')
  }

  // Night owl: 10PM - 5AM
  if (hour >= 22 || hour < 5) {
    unlock('nightOwl')
  }

  // Night explorer: midnight - 3AM
  if (hour >= 0 && hour < 4) {
    unlock('nightExplorer')
  }

  // Weekend warrior: Saturday (6) or Sunday (0)
  if (day === 0 || day === 6) {
    unlock('weekendWarrior')
  }
}

// Track clicks
const handleClick = () => {
  clickCount.value++
  if (clickCount.value >= 50 && !isUnlocked('clickHappy')) {
    unlock('clickHappy')
  }
}

// Track scroll distance
const handleScroll = () => {
  const currentScrollY = window.scrollY
  const scrollDiff = Math.abs(currentScrollY - lastScrollY.value)
  totalScrolled.value += scrollDiff
  lastScrollY.value = currentScrollY

  if (totalScrolled.value >= 10000 && !isUnlocked('scrollMaster')) {
    unlock('scrollMaster')
  }

  // Boomerang: scrolled to bottom then back to top
  const scrollHeight = document.documentElement.scrollHeight
  const clientHeight = document.documentElement.clientHeight
  const scrollPercent = currentScrollY / (scrollHeight - clientHeight)

  if (scrollPercent >= 0.99) {
    reachedBottom.value = true
  }
  if (reachedBottom.value && scrollPercent < 0.01 && !isUnlocked('boomerang')) {
    unlock('boomerang')
  }
}

// Track time spent
const startTimeTracking = () => {
  const startTime = Date.now()

  timeSpentInterval.value = setInterval(() => {
    const elapsed = (Date.now() - startTime) / 1000 / 60 // minutes
    if (elapsed >= 5 && !isUnlocked('timeSpent')) {
      unlock('timeSpent')
    }
    if (elapsed >= 10 && !isUnlocked('devotedReader')) {
      unlock('devotedReader')
    }
    if (isUnlocked('timeSpent') && isUnlocked('devotedReader') && timeSpentInterval.value) {
      clearInterval(timeSpentInterval.value)
    }
  }, 10000) // Check every 10 seconds
}

// Check 3D load completion for patience achievement
const checkPatienceAchievement = () => {
  // Unlock after page fully loads (including 3D)
  window.addEventListener('load', () => {
    setTimeout(() => {
      unlock('patience')
    }, 3000) // Wait 3 seconds after full load
  }, { once: true })
}

// Check device type
const checkDeviceAchievements = () => {
  if (navigator.maxTouchPoints > 0 && window.innerWidth < 768) {
    unlock('mobileScout')
  }
}

// Listen for print attempts
const handleBeforePrint = () => {
  unlock('printReady')
}

const setupPrintListener = () => {
  window.addEventListener('beforeprint', handleBeforePrint)
}

// Track unique visit days for frequent flyer
const VISIT_DAYS_STORAGE_KEY = 'wifsimster_visit_days'

const checkFrequentFlyer = () => {
  const today = new Date().toISOString().split('T')[0]
  const savedDays = JSON.parse(localStorage.getItem(VISIT_DAYS_STORAGE_KEY) || '[]') as string[]

  if (!savedDays.includes(today)) {
    savedDays.push(today)
    localStorage.setItem(VISIT_DAYS_STORAGE_KEY, JSON.stringify(savedDays))
  }

  if (savedDays.length >= 3) {
    unlock('frequentFlyer')
  }
}

// Track Tab key presses
const handleKeyboardTracking = (e: KeyboardEvent) => {
  if (e.key === 'Tab') {
    tabKeyCount.value++
    if (tabKeyCount.value >= 10 && !isUnlocked('keyboardNinja')) {
      unlock('keyboardNinja')
    }
  }
}

// Buffer keystrokes and detect secret words
const handleSecretWord = (e: KeyboardEvent) => {
  if (e.key.length === 1) {
    secretBuffer.value += e.key.toLowerCase()
    // Keep buffer manageable
    if (secretBuffer.value.length > 20) {
      secretBuffer.value = secretBuffer.value.slice(-20)
    }
    if (secretBuffer.value.includes('hello') || secretBuffer.value.includes('bonjour')) {
      unlock('secretWhisper')
      secretBuffer.value = ''
    }
  }
}

onMounted(() => {
  // Guard the FPS target: the monitor auto-degrades quality (high → low →
  // minimal) whenever sustained FPS falls below 70% of the target, so the
  // higher desktop DPR/texture budget can never lock the page under 60fps.
  startFPSMonitoring()

  // Auto-enable FPS display in development
  if (import.meta.env.DEV && fpsDisplayRef.value) {
    fpsDisplayRef.value.start()
  }

  checkVisitAchievements()
  checkTimeAchievements()
  checkPatienceAchievement()
  checkDeviceAchievements()
  checkFrequentFlyer()
  setupPrintListener()
  startTimeTracking()

  lastScrollY.value = window.scrollY
  window.addEventListener('click', handleClick)
  window.addEventListener('scroll', handleScroll, { passive: true })
  window.addEventListener('keydown', handleKeyboardTracking)
  window.addEventListener('keydown', handleSecretWord)
})

onUnmounted(() => {
  window.removeEventListener('click', handleClick)
  window.removeEventListener('scroll', handleScroll)
  window.removeEventListener('keydown', handleKeyboardTracking)
  window.removeEventListener('keydown', handleSecretWord)
  window.removeEventListener('beforeprint', handleBeforePrint)
  if (timeSpentInterval.value) {
    clearInterval(timeSpentInterval.value)
  }
})
</script>

<template>
  <div class="min-h-screen bg-(--color-bg-primary)">
    <!-- Modern aurora-mesh backdrop behind everything -->
    <AppBackground />

    <!-- Fixed UI Elements -->
    <header class="fixed top-4 right-4 z-100 flex gap-3 items-center sm:top-2 sm:right-2 sm:gap-2">
      <AchievementsIndicator />
      <LanguageSwitcher />
    </header>
    
    <!-- Table of Contents (Desktop only) -->
    <TableOfContents />
    
    <!-- Main Content -->
    <RouterView />

    <!-- Three.js space companion cruising across every section -->
    <CompanionOverlay />

    <!-- Achievement Toast -->
    <AchievementToast
      v-if="showAchievement && currentAchievement"
      :achievement="currentAchievement"
      @close="dismissAchievement"
    />
    
    <!-- FPS Display -->
    <FPSDisplay ref="fpsDisplayRef" />
  </div>
</template>
