// src/presentation/views/HomeView.tsx
import HeroSection from '@presentation/components/sections/HeroSection'
import AboutSection from '@presentation/components/sections/AboutSection'
import ExperienceSection from '@presentation/components/sections/ExperienceSection'
import MotivationSection from '@presentation/components/sections/MotivationSection'
import SkillsSection from '@presentation/components/sections/SkillsSection'
import MakerSection from '@presentation/components/sections/MakerSection'
import ProjectsSection from '@presentation/components/sections/ProjectsSection'
import BooksSection from '@presentation/components/sections/BooksSection'
import ContactSection from '@presentation/components/sections/ContactSection'

export default function HomeView() {
  return (
    <main className="w-full">
      <HeroSection />
      <AboutSection />
      <MotivationSection />
      <ExperienceSection />
      <SkillsSection />
      <MakerSection />
      <ProjectsSection />
      <BooksSection />
      <ContactSection />
    </main>
  )
}

// src/presentation/views/HomeView.vue
<script setup lang="ts">
import HeroSection from '@presentation/components/sections/HeroSection.vue'
import AboutSection from '@presentation/components/sections/AboutSection.vue'
import ExperienceSection from '@presentation/components/sections/ExperienceSection.vue'
import MotivationSection from '@presentation/components/sections/MotivationSection.vue'
import SkillsSection from '@presentation/components/sections/SkillsSection.vue'
import MakerSection from '@presentation/components/sections/MakerSection.vue'
import ProjectsSection from '@presentation/components/sections/ProjectsSection.vue'
import BooksSection from '@presentation/components/sections/BooksSection.vue'
import ContactSection from '@presentation/components/sections/ContactSection.vue'
</script>

<template>
  <main class="w-full">
    <HeroSection />
    <AboutSection />
    <MotivationSection />
    <ExperienceSection />
    <SkillsSection />
    <MakerSection />
    <ProjectsSection />
    <BooksSection />
    <ContactSection />
  </main>
</template>
